-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 14:21:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Projectdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projectdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projectdb` DEFAULT CHARACTER SET utf8 ;
USE `Projectdb` ;

-- -----------------------------------------------------
-- Table `Projectdb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projectdb`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderName` VARCHAR(45) NULL,
  `orderPrice` DECIMAL(2) NULL,
  `orderQuantity` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projectdb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projectdb`.`customers` (
  `id` INT NULL AUTO_INCREMENT,
  `customerName` VARCHAR(45) NOT NULL,
  `customerEmail` VARCHAR(45) NOT NULL,
  `customerPassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projectdb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projectdb`.`product` (
  `id` INT NOT NULL,
  `productName` VARCHAR(45) NULL,
  `productPrice` DECIMAL(4,2) NULL,
  `productStock` INT NULL,
  `productImage` VARCHAR(45) NULL,
  `productdescription` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projectdb`.`size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projectdb`.`size` (
  `id` INT NOT NULL,
  `small` CHAR NULL,
  `meduim` CHAR NULL,
  `large` CHAR NULL,
  `X Large` CHAR NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projectdb`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projectdb`.`gender` (
  `id` INT NOT NULL,
  `male` CHAR NULL,
  `female` CHAR NULL,
  `gendercol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projectdb`.`customers_has_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projectdb`.`customers_has_orders` (
  `customers_id` INT NOT NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`customers_id`, `orders_id`),
  INDEX `fk_customers_has_orders_orders1_idx` (`orders_id` ASC) VISIBLE,
  INDEX `fk_customers_has_orders_customers_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_has_orders_customers`
    FOREIGN KEY (`customers_id`)
    REFERENCES `Projectdb`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_has_orders_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `Projectdb`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projectdb`.`product_has_gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projectdb`.`product_has_gender` (
  `product_id` INT NOT NULL,
  `gender_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `gender_id`),
  INDEX `fk_product_has_gender_gender1_idx` (`gender_id` ASC) VISIBLE,
  INDEX `fk_product_has_gender_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_gender_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Projectdb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_gender_gender1`
    FOREIGN KEY (`gender_id`)
    REFERENCES `Projectdb`.`gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projectdb`.`product_has_size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projectdb`.`product_has_size` (
  `product_id` INT NOT NULL,
  `size_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `size_id`),
  INDEX `fk_product_has_size_size1_idx` (`size_id` ASC) VISIBLE,
  INDEX `fk_product_has_size_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_size_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Projectdb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_size_size1`
    FOREIGN KEY (`size_id`)
    REFERENCES `Projectdb`.`size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projectdb`.`orders_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projectdb`.`orders_has_product` (
  `orders_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`orders_id`, `product_id`),
  INDEX `fk_orders_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_orders_has_product_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_product_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `Projectdb`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Projectdb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
